{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package stopwords to\n",
      "[nltk_data]     C:\\Users\\srisa_000\\AppData\\Roaming\\nltk_data...\n",
      "[nltk_data]   Package stopwords is already up-to-date!\n"
     ]
    }
   ],
   "source": [
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "\n",
    "dataset = pd.read_csv('Book2.csv')\n",
    "\n",
    "import re\n",
    "import nltk\n",
    "nltk.download('stopwords')\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.stem.porter import PorterStemmer\n",
    "ps = PorterStemmer()\n",
    "data=[]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#pre-processing:--\n",
    "\n",
    "for i in range(0,len(dataset)):\n",
    "        review=dataset[\"comment_text\"][i]\n",
    "        #review=\"food is tasty\"\n",
    "        review = re.sub('[^a-zA-Z]', ' ', review)\n",
    "        review = review.lower()\n",
    "        review = review.split()\n",
    "        review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]\n",
    "        review = ' '.join(review)\n",
    "        data.append(review)\n",
    "        \n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>comment_text</th>\n",
       "      <th>toxic</th>\n",
       "      <th>severe_toxic</th>\n",
       "      <th>obscene</th>\n",
       "      <th>threat</th>\n",
       "      <th>insult</th>\n",
       "      <th>identity_hate</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0000997932d777bf</td>\n",
       "      <td>Explanation\\nWhy the edits made under my usern...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>000103f0d9cfb60f</td>\n",
       "      <td>D'aww! He matches this background colour I'm s...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>000113f07ec002fd</td>\n",
       "      <td>Hey man, I'm really not trying to edit war. It...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0001b41b1c6bb37e</td>\n",
       "      <td>\"\\nMore\\nI can't make any real suggestions on ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0001d958c54c6e35</td>\n",
       "      <td>You, sir, are my hero. Any chance you remember...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>00025465d4725e87</td>\n",
       "      <td>\"\\n\\nCongratulations from me as well, use the ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>0002bcb3da6cb337</td>\n",
       "      <td>COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>00031b1e95af7921</td>\n",
       "      <td>Your vandalism to the Matt Shirvington article...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>00037261f536c51d</td>\n",
       "      <td>Sorry if the word 'nonsense' was offensive to ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>00040093b2687caa</td>\n",
       "      <td>alignment on this subject and which are contra...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>0005300084f90edc</td>\n",
       "      <td>\"\\nFair use rationale for Image:Wonju.jpg\\n\\nT...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>00054a5e18b50dd4</td>\n",
       "      <td>bbq \\n\\nbe a man and lets discuss it-maybe ove...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>0005c987bdfc9d4b</td>\n",
       "      <td>Hey... what is it..\\n@ | talk .\\nWhat is it......</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>0006f16e4e9f292e</td>\n",
       "      <td>Before you start throwing accusations and warn...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>00070ef96486d6f9</td>\n",
       "      <td>Oh, and the girl above started her arguments w...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>00078f8ce7eb276d</td>\n",
       "      <td>\"\\n\\nJuelz Santanas Age\\n\\nIn 2002, Juelz Sant...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>0007e25b2121310b</td>\n",
       "      <td>Bye! \\n\\nDon't look, come or think of comming ...</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>000897889268bc93</td>\n",
       "      <td>REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>0009801bd85e5806</td>\n",
       "      <td>The Mitsurugi point made no sense - why not ar...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>0009eaea3325de8c</td>\n",
       "      <td>Don't mean to bother you \\n\\nI see that you're...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>000b08c464718505</td>\n",
       "      <td>\"\\n\\n Regarding your recent edits \\n\\nOnce aga...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>000bfd0867774845</td>\n",
       "      <td>\"\\nGood to know. About me, yeah, I'm studying ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>000c0dfd995809fa</td>\n",
       "      <td>\"\\n\\n Snowflakes are NOT always symmetrical! \\...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>000c6a3f0cd3ba8e</td>\n",
       "      <td>\"\\n\\n The Signpost: 24 September 2012 \\n\\n Rea...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>000cfee90f50d471</td>\n",
       "      <td>\"\\n\\nRe-considering 1st paragraph edit?\\nI don...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>000eefc67a2c930f</td>\n",
       "      <td>Radial symmetry \\n\\nSeveral now extinct lineag...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>000f35deef84dc4a</td>\n",
       "      <td>There's no need to apologize. A Wikipedia arti...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>000ffab30195c5e1</td>\n",
       "      <td>Yes, because the mother of the child in the ca...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>0010307a3a50a353</td>\n",
       "      <td>\"\\nOk. But it will take a bit of work but I ca...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>0010833a96e1f886</td>\n",
       "      <td>\"== A barnstar for you! ==\\n\\n  The Real Life ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7029</th>\n",
       "      <td>12c0e0020dea5d90</td>\n",
       "      <td>The first sentence of the article is incorrect...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7030</th>\n",
       "      <td>12c0ee5c464dba1e</td>\n",
       "      <td>(oh, and I almost forgot  start uploading pict...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7031</th>\n",
       "      <td>12c10e54d53437ac</td>\n",
       "      <td>What do you mean it is hardly true I have prov...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7032</th>\n",
       "      <td>12c16ca6232d2e75</td>\n",
       "      <td>Thanks \\n\\nThanks for the very useful comments...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7033</th>\n",
       "      <td>12c2e39306bd2386</td>\n",
       "      <td>we are studying vilma's special subjet, photos...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7034</th>\n",
       "      <td>12c2fdfbdb130062</td>\n",
       "      <td>I also agree. It's relevent because Sanchez ma...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7035</th>\n",
       "      <td>12c3a337911c9820</td>\n",
       "      <td>REDIRECT Talk:Cape May – Lewes Ferry</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7036</th>\n",
       "      <td>12c82a67010c0fcf</td>\n",
       "      <td>\"\\n\\nAn illness has nothing to do with time/er...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7037</th>\n",
       "      <td>12c83c8361350f59</td>\n",
       "      <td>At least give me a chance to edit the page.</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7038</th>\n",
       "      <td>12c9096fcb45b243</td>\n",
       "      <td>Maybe you don't know everything there is to kn...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7039</th>\n",
       "      <td>12cb9adde11b897c</td>\n",
       "      <td>\"\\n\\nHi Math. Thanks for the page with the pic...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7040</th>\n",
       "      <td>12cb9cd8e808e724</td>\n",
       "      <td>IDIOT \\n\\nYOU JUST GO AROUND UNVALDALIZING WIK...</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7041</th>\n",
       "      <td>12cccfec304b68d7</td>\n",
       "      <td>\"\\n\\n Please do not continue to violate Wikipe...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7042</th>\n",
       "      <td>12cce60ae2162421</td>\n",
       "      <td>This is very similar to what I have so far dis...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7043</th>\n",
       "      <td>12ccf23584ff3559</td>\n",
       "      <td>Fuck off \\n\\nsee my page for more of my commen...</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7044</th>\n",
       "      <td>12cd3edc98ef6fcb</td>\n",
       "      <td>Nice.  I am going to see how long it takes her...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7045</th>\n",
       "      <td>12ce2fc57100618e</td>\n",
       "      <td>REDIRECT Talk:Igor Kojić (footballer)</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7046</th>\n",
       "      <td>12ce37e700de2cd1</td>\n",
       "      <td>\"\\n\\n Hi! Have as look at the definition of \"\"...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7047</th>\n",
       "      <td>12ce3b95e592919a</td>\n",
       "      <td>\"\\n\\nHi, I was referring to Princes Risborough...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7048</th>\n",
       "      <td>12ce6478b6147e20</td>\n",
       "      <td>You have not replied to my post above, which m...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7049</th>\n",
       "      <td>12cec4caf037b44f</td>\n",
       "      <td>The new York times policy to suppress news of ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7050</th>\n",
       "      <td>12ceca2532087b6d</td>\n",
       "      <td>\"\\nReady! I'll take it to all right now. 110 \"</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7051</th>\n",
       "      <td>12cfb877f2b488ab</td>\n",
       "      <td>And those 3 things right there is all that mat...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7052</th>\n",
       "      <td>12cfe11d1018f5fa</td>\n",
       "      <td>Bedfordshire Blue Raiders \\n\\nHello, \\n\\nI see...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7053</th>\n",
       "      <td>12d001c8cbaa81ff</td>\n",
       "      <td>\"\\n\\nIf you are looking for a new challenge - ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7054</th>\n",
       "      <td>12d0ea8f29de02f2</td>\n",
       "      <td>Damage Controversy\\n\\nUnfortunately, I am unab...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7055</th>\n",
       "      <td>12d17284171e6cb1</td>\n",
       "      <td>Regarding you being a homosexual\\nYou are clea...</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7056</th>\n",
       "      <td>12d1dba0c92b7545</td>\n",
       "      <td>\"\\n\\nI would like to know what you think of th...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7057</th>\n",
       "      <td>12d1e012dbe63af9</td>\n",
       "      <td>ALSO-what of this Thomas Jefferson had it repr...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7058</th>\n",
       "      <td>12d2e8f8f10af4b8</td>\n",
       "      <td>The othello Error (Ekman, 1985) refers to the ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>7059 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                    id                                       comment_text  \\\n",
       "0     0000997932d777bf  Explanation\\nWhy the edits made under my usern...   \n",
       "1     000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   \n",
       "2     000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   \n",
       "3     0001b41b1c6bb37e  \"\\nMore\\nI can't make any real suggestions on ...   \n",
       "4     0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   \n",
       "5     00025465d4725e87  \"\\n\\nCongratulations from me as well, use the ...   \n",
       "6     0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   \n",
       "7     00031b1e95af7921  Your vandalism to the Matt Shirvington article...   \n",
       "8     00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...   \n",
       "9     00040093b2687caa  alignment on this subject and which are contra...   \n",
       "10    0005300084f90edc  \"\\nFair use rationale for Image:Wonju.jpg\\n\\nT...   \n",
       "11    00054a5e18b50dd4  bbq \\n\\nbe a man and lets discuss it-maybe ove...   \n",
       "12    0005c987bdfc9d4b  Hey... what is it..\\n@ | talk .\\nWhat is it......   \n",
       "13    0006f16e4e9f292e  Before you start throwing accusations and warn...   \n",
       "14    00070ef96486d6f9  Oh, and the girl above started her arguments w...   \n",
       "15    00078f8ce7eb276d  \"\\n\\nJuelz Santanas Age\\n\\nIn 2002, Juelz Sant...   \n",
       "16    0007e25b2121310b  Bye! \\n\\nDon't look, come or think of comming ...   \n",
       "17    000897889268bc93   REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski   \n",
       "18    0009801bd85e5806  The Mitsurugi point made no sense - why not ar...   \n",
       "19    0009eaea3325de8c  Don't mean to bother you \\n\\nI see that you're...   \n",
       "20    000b08c464718505  \"\\n\\n Regarding your recent edits \\n\\nOnce aga...   \n",
       "21    000bfd0867774845  \"\\nGood to know. About me, yeah, I'm studying ...   \n",
       "22    000c0dfd995809fa  \"\\n\\n Snowflakes are NOT always symmetrical! \\...   \n",
       "23    000c6a3f0cd3ba8e  \"\\n\\n The Signpost: 24 September 2012 \\n\\n Rea...   \n",
       "24    000cfee90f50d471  \"\\n\\nRe-considering 1st paragraph edit?\\nI don...   \n",
       "25    000eefc67a2c930f  Radial symmetry \\n\\nSeveral now extinct lineag...   \n",
       "26    000f35deef84dc4a  There's no need to apologize. A Wikipedia arti...   \n",
       "27    000ffab30195c5e1  Yes, because the mother of the child in the ca...   \n",
       "28    0010307a3a50a353  \"\\nOk. But it will take a bit of work but I ca...   \n",
       "29    0010833a96e1f886  \"== A barnstar for you! ==\\n\\n  The Real Life ...   \n",
       "...                ...                                                ...   \n",
       "7029  12c0e0020dea5d90  The first sentence of the article is incorrect...   \n",
       "7030  12c0ee5c464dba1e  (oh, and I almost forgot  start uploading pict...   \n",
       "7031  12c10e54d53437ac  What do you mean it is hardly true I have prov...   \n",
       "7032  12c16ca6232d2e75  Thanks \\n\\nThanks for the very useful comments...   \n",
       "7033  12c2e39306bd2386  we are studying vilma's special subjet, photos...   \n",
       "7034  12c2fdfbdb130062  I also agree. It's relevent because Sanchez ma...   \n",
       "7035  12c3a337911c9820               REDIRECT Talk:Cape May – Lewes Ferry   \n",
       "7036  12c82a67010c0fcf  \"\\n\\nAn illness has nothing to do with time/er...   \n",
       "7037  12c83c8361350f59        At least give me a chance to edit the page.   \n",
       "7038  12c9096fcb45b243  Maybe you don't know everything there is to kn...   \n",
       "7039  12cb9adde11b897c  \"\\n\\nHi Math. Thanks for the page with the pic...   \n",
       "7040  12cb9cd8e808e724  IDIOT \\n\\nYOU JUST GO AROUND UNVALDALIZING WIK...   \n",
       "7041  12cccfec304b68d7  \"\\n\\n Please do not continue to violate Wikipe...   \n",
       "7042  12cce60ae2162421  This is very similar to what I have so far dis...   \n",
       "7043  12ccf23584ff3559  Fuck off \\n\\nsee my page for more of my commen...   \n",
       "7044  12cd3edc98ef6fcb  Nice.  I am going to see how long it takes her...   \n",
       "7045  12ce2fc57100618e              REDIRECT Talk:Igor Kojić (footballer)   \n",
       "7046  12ce37e700de2cd1  \"\\n\\n Hi! Have as look at the definition of \"\"...   \n",
       "7047  12ce3b95e592919a  \"\\n\\nHi, I was referring to Princes Risborough...   \n",
       "7048  12ce6478b6147e20  You have not replied to my post above, which m...   \n",
       "7049  12cec4caf037b44f  The new York times policy to suppress news of ...   \n",
       "7050  12ceca2532087b6d     \"\\nReady! I'll take it to all right now. 110 \"   \n",
       "7051  12cfb877f2b488ab  And those 3 things right there is all that mat...   \n",
       "7052  12cfe11d1018f5fa  Bedfordshire Blue Raiders \\n\\nHello, \\n\\nI see...   \n",
       "7053  12d001c8cbaa81ff  \"\\n\\nIf you are looking for a new challenge - ...   \n",
       "7054  12d0ea8f29de02f2  Damage Controversy\\n\\nUnfortunately, I am unab...   \n",
       "7055  12d17284171e6cb1  Regarding you being a homosexual\\nYou are clea...   \n",
       "7056  12d1dba0c92b7545  \"\\n\\nI would like to know what you think of th...   \n",
       "7057  12d1e012dbe63af9  ALSO-what of this Thomas Jefferson had it repr...   \n",
       "7058  12d2e8f8f10af4b8  The othello Error (Ekman, 1985) refers to the ...   \n",
       "\n",
       "      toxic  severe_toxic  obscene  threat  insult  identity_hate  \n",
       "0         0             0        0       0       0              0  \n",
       "1         0             0        0       0       0              0  \n",
       "2         0             0        0       0       0              0  \n",
       "3         0             0        0       0       0              0  \n",
       "4         0             0        0       0       0              0  \n",
       "5         0             0        0       0       0              0  \n",
       "6         1             1        1       0       1              0  \n",
       "7         0             0        0       0       0              0  \n",
       "8         0             0        0       0       0              0  \n",
       "9         0             0        0       0       0              0  \n",
       "10        0             0        0       0       0              0  \n",
       "11        0             0        0       0       0              0  \n",
       "12        1             0        0       0       0              0  \n",
       "13        0             0        0       0       0              0  \n",
       "14        0             0        0       0       0              0  \n",
       "15        0             0        0       0       0              0  \n",
       "16        1             0        0       0       0              0  \n",
       "17        0             0        0       0       0              0  \n",
       "18        0             0        0       0       0              0  \n",
       "19        0             0        0       0       0              0  \n",
       "20        0             0        0       0       0              0  \n",
       "21        0             0        0       0       0              0  \n",
       "22        0             0        0       0       0              0  \n",
       "23        0             0        0       0       0              0  \n",
       "24        0             0        0       0       0              0  \n",
       "25        0             0        0       0       0              0  \n",
       "26        0             0        0       0       0              0  \n",
       "27        0             0        0       0       0              0  \n",
       "28        0             0        0       0       0              0  \n",
       "29        0             0        0       0       0              0  \n",
       "...     ...           ...      ...     ...     ...            ...  \n",
       "7029      0             0        0       0       0              0  \n",
       "7030      0             0        0       0       0              0  \n",
       "7031      0             0        0       0       0              0  \n",
       "7032      0             0        0       0       0              0  \n",
       "7033      0             0        0       0       0              0  \n",
       "7034      0             0        0       0       0              0  \n",
       "7035      0             0        0       0       0              0  \n",
       "7036      0             0        0       0       1              1  \n",
       "7037      0             0        0       0       0              0  \n",
       "7038      0             0        0       0       0              0  \n",
       "7039      0             0        0       0       0              0  \n",
       "7040      1             0        0       0       1              0  \n",
       "7041      0             0        0       0       0              0  \n",
       "7042      0             0        0       0       0              0  \n",
       "7043      1             0        1       0       0              0  \n",
       "7044      0             0        0       0       0              0  \n",
       "7045      0             0        0       0       0              0  \n",
       "7046      0             0        0       0       0              0  \n",
       "7047      0             0        0       0       0              0  \n",
       "7048      0             0        0       0       0              0  \n",
       "7049      0             0        0       0       0              0  \n",
       "7050      0             0        0       0       0              0  \n",
       "7051      0             0        0       0       0              0  \n",
       "7052      0             0        0       0       0              0  \n",
       "7053      0             0        0       0       0              0  \n",
       "7054      0             0        0       0       0              0  \n",
       "7055      1             0        1       0       1              1  \n",
       "7056      0             0        0       0       0              0  \n",
       "7057      0             0        0       0       0              0  \n",
       "7058      0             0        0       0       0              0  \n",
       "\n",
       "[7059 rows x 8 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[0 0 0 0 0 0]\n",
      " [0 0 0 0 0 0]\n",
      " [0 0 0 0 0 0]\n",
      " ...\n",
      " [0 0 0 0 0 0]\n",
      " [0 0 0 0 0 0]\n",
      " [0 0 0 0 0 0]]\n",
      "(7059, 1500)\n",
      "(7059, 6)\n"
     ]
    }
   ],
   "source": [
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "cv = CountVectorizer(max_features=1500)\n",
    "X = cv.fit_transform(data).toarray()\n",
    "y=dataset.iloc[:,2:].values\n",
    "print(y)\n",
    "print(X.shape)\n",
    "print(y.shape)\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(7059, 8)"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dataset.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>comment_text</th>\n",
       "      <th>toxic</th>\n",
       "      <th>severe_toxic</th>\n",
       "      <th>obscene</th>\n",
       "      <th>threat</th>\n",
       "      <th>insult</th>\n",
       "      <th>identity_hate</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0000997932d777bf</td>\n",
       "      <td>Explanation\\nWhy the edits made under my usern...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>000103f0d9cfb60f</td>\n",
       "      <td>D'aww! He matches this background colour I'm s...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>000113f07ec002fd</td>\n",
       "      <td>Hey man, I'm really not trying to edit war. It...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0001b41b1c6bb37e</td>\n",
       "      <td>\"\\nMore\\nI can't make any real suggestions on ...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0001d958c54c6e35</td>\n",
       "      <td>You, sir, are my hero. Any chance you remember...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 id                                       comment_text  toxic  \\\n",
       "0  0000997932d777bf  Explanation\\nWhy the edits made under my usern...      0   \n",
       "1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   \n",
       "2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   \n",
       "3  0001b41b1c6bb37e  \"\\nMore\\nI can't make any real suggestions on ...      0   \n",
       "4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   \n",
       "\n",
       "   severe_toxic  obscene  threat  insult  identity_hate  \n",
       "0             0        0       0       0              0  \n",
       "1             0        0       0       0              0  \n",
       "2             0        0       0       0              0  \n",
       "3             0        0       0       0              0  \n",
       "4             0        0       0       0              0  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dataset.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>category</th>\n",
       "      <th>number_of_comments</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>toxic</td>\n",
       "      <td>707</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>severe_toxic</td>\n",
       "      <td>72</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>obscene</td>\n",
       "      <td>384</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>threat</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>insult</td>\n",
       "      <td>363</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>identity_hate</td>\n",
       "      <td>66</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        category  number_of_comments\n",
       "0          toxic                 707\n",
       "1   severe_toxic                  72\n",
       "2        obscene                 384\n",
       "3         threat                  26\n",
       "4         insult                 363\n",
       "5  identity_hate                  66"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_toxic = dataset.drop(['id', 'comment_text'], axis=1)\n",
    "#print(df_toxic)\n",
    "counts = []\n",
    "categories = list(df_toxic.columns.values)\n",
    "for i in categories:\n",
    "    counts.append((i, df_toxic[i].sum()))\n",
    "df_stats = pd.DataFrame(counts, columns=['category', 'number_of_comments'])\n",
    "df_stats\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 7059 entries, 0 to 7058\n",
      "Data columns (total 8 columns):\n",
      "id               7059 non-null object\n",
      "comment_text     7059 non-null object\n",
      "toxic            7059 non-null int64\n",
      "severe_toxic     7059 non-null int64\n",
      "obscene          7059 non-null int64\n",
      "threat           7059 non-null int64\n",
      "insult           7059 non-null int64\n",
      "identity_hate    7059 non-null int64\n",
      "dtypes: int64(6), object(2)\n",
      "memory usage: 441.3+ KB\n"
     ]
    }
   ],
   "source": [
    "dataset.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 0, 'category')"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAfsAAAGHCAYAAAC3a/toAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvOIA7rQAAIABJREFUeJzt3XmcHVWd///Xm4QlJEBYQgtJICJhkwBCZFc7gOwQZiCig2yDRhFZRmRxR8WfoDIogoz5DUpAJSC7LAoGAwICJiCEzSFAICSQBEhCEkAMfL5/1Glz0+nuVNLVXdWV9/PxuI++daruuZ97+nZ/qk6dOqWIwMzMzOprlbIDMDMzs67lZG9mZlZzTvZmZmY152RvZmZWc072ZmZmNedkb2ZmVnNO9mYNJF0u6dyS3luSfilpjqSHyojBzOrJyd4qTdJUSTMl9W0o+4ykCSWG1VX2BD4ODIqIncsOpqtJGiIpJPUuO5aiSGqW9FLZcZi15mRvPUFv4NSyg1heknot50s2BaZGxMKuiMfaVpedjbp8DusaTvbWE/wQ+LKk/q1XtHV0KGmCpM+k58dJuk/ShZLmSnpO0u6pfJqkWZKObVXtBpLulDRf0t2SNm2oe6u07nVJf5f0iYZ1l0u6VNJtkhYCI9qId2NJN6fXT5H02VR+AvC/wG6SFkj6dlsNIemzkp5KsT0pacdUvnX63HMlPSHp0FZx/UzS7anu+yS9T9KP0ymDpyV9qGH7qZLOkPSYpIWSLpPUlF4/X9IfJa3bsP2uku5P7/2opOZWv4vvpvecL+kOSRuk1fekn3NTXLtJ2jy1+TxJr0q6up12aPm9j5Y0Q9LLkk5vWL+KpLMlPSvpNUnXSFqv1WtPkPQicFc77zFS0t8kvZHq2T+VH9/wO3hO0udSeV/gdmDj9HkWpN93u7Gk1x0j6YW07hup/fdJ61ZPv6cZ6fFjSaundc2SXpJ0lqRXgF9KelzSIQ11r5racYe2PqOtRCLCDz8q+wCmAvsA1wPnprLPABPS8yFAAL0bXjMB+Ex6fhywCDge6AWcC7wIXAKsDuwLzAf6pe0vT8sfTet/Atyb1vUFpqW6egM7Aq8CH2x47TxgD7Id6TXa+Dx3Az8D1gB2AGYDezfEem8HbTEKmA58GBCwOVlvwKrAFOCrwGrAXukzbNkQ16vATul97wKeB45paJM/tWrzB4AmYCAwC3gY+FBqk7uAb6VtBwKvAQemz/zxtDyg4XfxLLAF0Cctn9fB7+4q4Gst7Qfs2U5btLz2qvR7GZbacp+0/rT0GQalmH8OXNXqtVek1/Zpo/6d0+/y4ymWgcBWad1BwAfS7+BjwJvAjmldM/BSq7o6imUbYAHZKZzVgB8B/2z4HN9Jr90QGADcD3y34b0WAeenevsAZwJXN7z3SGBy2X/HfpT/KD0AP/zo6MHiZL9t+uc7gOVP9s80rBuWtm9qKHsN2CE9vxwY17CuH/AuMBg4Evhzq/h+zuLEdzlwRQefZXCqa62Gsu8DlzfE2lGy/wNwahvlHwFeAVZpKLsKOKchrv+/Yd3JwFOt2mRuqzY/qmH5OuDSVq+/MT0/C7iyjTiPbfhdfL1h3ReA33fwu7sCGEM2bqGj70XLa7dqKPsBcFl6/hRpJyotb0SWRHs3vHazDur/OXBhzu/ojS2/F9pO9h3F8k1S4k/r1gTeYXGyfxY4sGH9fmSnelre6x0adiqBjcl29NZOy9cCZ3bn36wf1Xy4G996hIh4HLgFOHsFXj6z4flbqb7WZf0alqc1vO8C4HWyf6KbAruk7uq5kuYCRwHva+u1bdgYeD0i5jeUvUB21JjHYLJ//m3VOy0i3uug3taft6PPvzzbbwqMatUme5IltBavNDx/s433anQm2RHzQ+l0xH92sC0s2d4vkLVFS1w3NMT0FNmOVlM7r22tvbZG0gGSHkinYuaS9Wps0Na2OWLZmCW/b2+S7Xy22Dh9rrY+I8DsiHi74fUzgPuAw5Wd9joA+HUHsdlKwgM6rCf5Fll38gUNZS2D2dYE3kjPG5Pvihjc8kRSP2A9YAbZP+W7I+LjHby2o9tIzgDWk7RWQ8LfhKxrPo9pZN3HbdU7WNIqDQl/E+D/ctbbGdPIjuw/uwKvXaqtIuIVoGUcw57AHyXdExFT2qljMPB0er4JWVu0xPWfEXFf6xdIGtLe+zdos63T+fLryE6B3BQR/5R0I9kOSnt1dhTLy8CWDct9gPUbNplBtrPwRFpu/Iztvd9Yst6v3sBfIiLv98tqzEf21mOkf/hXA6c0lM0mS5afltQrHQm2lRCXx4GS9pS0GvBd4MGImEbWs7CFpKPTwKdVJX1Y0tY5459Gds71+5LWkLQdcAL5j7z+l2yg4k7KbK5s8OCDZDs9Z6aYmoFDgHHL86FX0K+AQyTtl9p/jTRwbFCO184G3gM2aymQNKrhtXPIktm7HdTxDUlrSvog2ViKlgF9/wN8L7UPkgZIGrkcn+sy4HhJe6cBdgMlbUV2Xn31FPsiSQeQjftoMRNYX9I6DWUdxXItWfvtnr5v32bxjgNkp2O+nl6zAVm3/6+WEfuNZONJTiU7LWLmZG89znfIBlU1+ixwBln35wfJEmpn/IasF+F1skFtRwGko/F9gU+SHV29wuLBUXl9iuyc8QzgBrLz/XfmeWFE/Bb4XopvPtk/9fUi4h3gULIu21fJBgAeExFPt1dXUdIOzEiywYGzyY5izyDH/5bUZf094L7Uxb0r2eDDByUtAG4mOxf+fAfV3E02OHE88KOIuCOV/yS9/g5J88kGue2yHJ/rIbKdhwvJxorcDWyavgOnANeQ7Yz8R3qfltc9TZagn0ufaeOOYomIJ8jGQIwDXib7vc4C/pGqPBeYCDwGTCbr2epw0qeIeIus9+H9ZANbzVBERz1ZZmbVk7rinwdWjYhF5UZTnHTaaC4wdBk7Ocuq55vAFhHx6cKCsx7NR/ZmZiWSdEg6FdGX7NK7yWRXRKxofeuRnR4aU0yEVgdO9mZm5RpJdlpnBjAU+GSsYJerskmapgG3R8Q9y9reVh7uxjczM6s5H9mbmZnVXG2us99ggw1iyJAhZYexhIULF9K3b+uB49YWt1U+bqd83E75ua3yqWI7TZo06dWIGJBn29ok+yFDhjBx4sSyw1jChAkTaG5uLjuMHsFtlY/bKR+3U35uq3yq2E6SXlj2Vhl345uZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1Vy3zI0vaUvg6oaizYBvAlek8iHAVOATETFHkoCfAAcCbwLHRcTD3RErwJCzby2kntOHLeK4guqaet5BhdRjZmYrn245so+Iv0fEDhGxA7ATWQK/ATgbGB8RQ4HxaRngAGBoeowGLu2OOM3MzOqojG78vYFnI+IFYCQwNpWPBQ5Lz0cCV0TmAaC/pI26P1QzM7OeTxHRvW8o/QJ4OCIuljQ3Ivo3rJsTEetKugU4LyLuTeXjgbMiYmKrukaTHfnT1NS007hx4wqJcfL0eYXU09QHZr5VSFUMG7hOMRVV1IIFC+jXr1/ZYVSe2ykft1N+bqt8qthOI0aMmBQRw/Ns2633s5e0GnAo8JVlbdpG2VJ7JRExBhgDMHz48CjqXsNFnWc/fdgiLphcTBNPPaq5kHqqqor3iq4it1M+bqf83Fb59PR26u5u/APIjupnpuWZLd3z6eesVP4SMLjhdYOAGd0WpZmZWY10d7L/FHBVw/LNwLHp+bHATQ3lxyizKzAvIl7uvjDNzMzqo9u68SWtCXwc+FxD8XnANZJOAF4ERqXy28guu5tCNnL/+O6K08zMrG66LdlHxJvA+q3KXiMbnd962wBO6qbQzMzMas0z6JmZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVXLcle0n9JV0r6WlJT0naTdJ6ku6U9Ez6uW7aVpIukjRF0mOSduyuOM3MzOqmO4/sfwL8PiK2ArYHngLOBsZHxFBgfFoGOAAYmh6jgUu7MU4zM7Na6ZZkL2lt4KPAZQAR8U5EzAVGAmPTZmOBw9LzkcAVkXkA6C9po+6I1czMrG4UEV3/JtIOwBjgSbKj+knAqcD0iOjfsN2ciFhX0i3AeRFxbyofD5wVERNb1Tua7MifpqamncaNG1dIvJOnzyuknqY+MPOtQqpi2MB1iqmoohYsWEC/fv3KDqPy3E75uJ3yc1vlU8V2GjFixKSIGJ5n295dHUzD++wInBwRD0r6CYu77NuiNsqW2iuJiDFkOxEMHz48mpubCwgVjjv71kLqOX3YIi6YXEwTTz2quZB6qmrChAkU9furM7dTPm6n/NxW+fT0duquc/YvAS9FxINp+Vqy5D+zpXs+/ZzVsP3ghtcPAmZ0U6xmZma10i3JPiJeAaZJ2jIV7U3WpX8zcGwqOxa4KT2/GTgmjcrfFZgXES93R6xmZmZ1013d+AAnA7+WtBrwHHA82c7GNZJOAF4ERqVtbwMOBKYAb6ZtzczMbAV0W7KPiL8BbQ0k2LuNbQM4qcuDMjMzWwl4Bj0zM7Oac7I3MzOrOSd7MzOzmnOyNzMzqzknezMzs5pzsjczM6s5J3szM7Oac7I3MzOrOSd7MzOzmnOyNzMzqzknezMzs5pzsjczM6s5J3szM7Oac7I3MzOrOSd7MzOzmnOyNzMzqzknezMzs5pzsjczM6s5J3szM7Oac7I3MzOrOSd7MzOzmnOyNzMzqzknezMzs5pzsjczM6s5J3szM7Oac7I3MzOrOSd7MzOzmnOyNzMzq7lcyV7SpyRtnZ5vKekeSXdJ2irvG0maKmmypL9JmpjK1pN0p6Rn0s91U7kkXSRpiqTHJO24Ih/OzMzM8h/Znwu8np7/CHgIuAf42XK+34iI2CEihqfls4HxETEUGJ+WAQ4AhqbHaODS5XwfMzMzS3rn3G5ARMyUtAawJ3AE8E/g1U6+/0igOT0fC0wAzkrlV0REAA9I6i9po4h4uZPvZ2ZmttJRlk+XsZH0LLAfMAw4MSL2lbQmMD0i1s31RtLzwBwggJ9HxBhJcyOif8M2cyJiXUm3AOdFxL2pfDxwVkRMbFXnaLIjf5qamnYaN25cnlCWafL0eYXU09QHZr5VSFUMG7hOMRVV1IIFC+jXr1/ZYVSe2ykft1N+bqt8qthOI0aMmNTQU96hvEf23wUmAe8CR6ayvYFHlyOuPSJihqQNgTslPd3BtmqjbKm9kogYA4wBGD58eDQ3Ny9HOO077uxbC6nn9GGLuGBy3ibu2NSjmgupp6omTJhAUb+/OnM75eN2ys9tlU9Pb6dc5+wj4nJgI2BQRNyZih8EPpn3jSJiRvo5C7gB2BmYKWkjgPRzVtr8JWBww8sHATPyvpeZmZkttjyX3vUBDpd0ZlruTc6eAUl9Ja3V8hzYF3gcuBk4Nm12LHBTen4zcEwalb8rMM/n683MzFZM3mT9MeA6YCKwB/ADspHyXwYOyVFFE3CDpJb3/E1E/F7SX4FrJJ0AvAiMStvfBhwITAHeBI7P+4HMzMxsSXlPKP8YODIixkuak8oeJOuKX6aIeA7Yvo3y18jO/bcuD+CknLGZmZlZB/J24w+JiPHpectAuXfIv7NgZmZmJcmb7J+UtF+rsn2AyQXHY2ZmZgXLe2R+OnCLpFuBPpJ+TnaufmSXRWZmZmaFyHvp3QPAdsATwC+A54GdI+KvXRibmZmZFSDvaPzVgdkR8YOGslUlrR4R/+iy6MzMzKzT8p6zvxPYqVXZTsAfig3HzMzMipY32Q8ju9Su0UO0cTmdmZmZVUveZD+PbGKcRk3AwmLDMTMzs6LlTfbXAb+RtK2kNSUNA64Arum60MzMzKwIeZP914CnyLru5wMPAH8HvtpFcZmZmVlBco3Gj4i3gZMkfRHYAHg1TWlrZmZmFZd7ultJ6wBbAv3SMgARcVeXRGZmZmaFyHud/XHAJcACsrvQtQhgs+LDMjMzs6LkPbL/HnBERNzelcGYmZlZ8fIO0OsN3NGVgZiZmVnXyJvszwe+Linv9mZmZlYRebvx/wt4H3CmpNcaV0TEJoVHZWZmZoXJm+w/3aVRmJmZWZfJe5393V0diJmZmXWNXOfgJa0u6XuSnpM0L5XtmybZMTMzswrLO+DuQmBb4Ciya+sBngBO7IqgzMzMrDh5z9n/G7B5RCyU9B5AREyXNLDrQjMzM7Mi5D2yf4dWOwaSBgCvtb25mZmZVUXeZP9bYKyk9wNI2gi4GBjXVYGZmZlZMfIm+68CU4HJQH/gGWAG8O2uCcvMzMyKssxz9mnWvD2BsyLitNR971vcmpmZ9RDLPLKPiPeAmyLiH2l5thO9mZlZz5G3G/8eSbt2aSRmZmbWJfJeevcCcLukm4BpLL7Wnoj4Zt43k9QLmAhMj4iD04C/ccB6wMPA0RHxjqTVgSuAnchG/B8ZEVPzvo+ZmZktlvfIvg9wI1mSHwQMTo9By/l+pwJPNSyfD1wYEUOBOcAJqfwEYE5EbE42oc/5y/k+ZmZmluQdoHclcF/LefsVIWkQcBDwPeBLkgTsBfxH2mQscA5wKTAyPQe4FrhYkjxWwMzMbPkpT/6UND8i1urUG0nXAt8H1gK+DBwHPJCO3pE0GLg9IraV9Diwf0S8lNY9C+wSEa+2qnM0MBqgqalpp3Hjirnsf/L0eYXU09QHZr5VSFUMG7hOMRVV1IIFC+jXr1/ZYVSe2ykft1N+bqt8qthOI0aMmBQRw/Nsm/ec/T2Sdo2IB1YkIEkHA7MiYpKk5pbiNjaNHOsWF0SMAcYADB8+PJqbm1tvskKOO/vWQuo5fdgiLpict4k7NvWo5kLqqaoJEyZQ1O+vztxO+bid8nNb5dPT26m7BujtARwq6UBgDWBt4MdAf0m9I2IR2fn/GWn7l8jGBLwkqTewDvB6zljNzMysQWcH6A3O8+KI+EpEDIqIIcAngbsi4ijgT8ARabNjgZvS85vTMmn9XT5fb2ZmtmJyHdlHxPFd9P5nAeMknQs8AlyWyi8DrpQ0heyI/pNd9P5mZma1lyvZS9qsvXUR8dzyvGFETAAmNLx25za2eRsYtTz1mlXVsLHDCqvrxH4ncvLYkwupa/Kxkwupx8yqL+85+ylkXfiNA+dautV7FRqRmZmZFSpvN/4S5/YlvQ/4FvDnrgjKzMzMipN3gN4SIuIV4DSy6+bNzMyswlYo2SdbAmsWFYiZmZl1jbwD9P7MkpParAl8EPhOVwRlZmZmxck7QO9/Wy0vBB6NiGcKjsfMzMwKlneA3tiuDsTMzMy6Rt5u/OvJbkX754ayjwCnRsQR7b/SzMyKdsnn7yqsrg13X1hIfSf9z14FRGNdJe8AvY8B97cq+wswothwzMzMrGh5k/3bQN9WZf2AfxYbjpmZmRUtb7L/A/BzSWsDpJ8XA7/vqsDMzMysGHmT/elkt6V9XdIsspvTrEM2sY6ZmZlVWN7R+HOAg9I0uYOBaWkWPTMzM6u4vKPx9wWmRsT/Aa+ksi2BTSLizi6Mz8zMzDopbzf+JcD8VmXzU7mZmZlVWN5kv2FEvNyq7GXgfQXHY2ZmZgXLm+yfk9R6xoRm4PliwzEzM7Oi5Z0b/xzgekmXAc8CHwCOTw8zMzOrsFxH9hFxE7Av2cQ6B6Wf+6VyMzMzq7C8R/ZExEPAQ10Yi5mZmXWBZR7ZSxoi6XJJ0yX9I/0cK2mz7gjQzMzMOqfDZC9pa+BhYEPga8Ch6ecAYGJab2ZmZhW2rG7884BLIuIbrcovl3Qu8APgkC6JzMzMzAqxrGT/UeDYdtZdgC+9MzMzq7xlnbPvRfu3sf1nWm9mZmYVtqxk/1fav5b+OGBiodGYmZlZ4ZbVjf8N4A/ppjfXkk2RuxEwiqx7f7+uDc/MzMw6q8Mj+4i4n2wyne2B8cDT6ef2wP5p/TJJWkPSQ5IelfSEpG+n8vdLelDSM5KulrRaKl89LU9J64es8Cc0MzNbyS3zOvuI+EtEfBRYi+xe9mtHxEci4r7leJ9/AHtFxPbADsD+knYFzgcujIihwBzghLT9CcCciNgcuDBtZ2ZmZisg741wiIi3ImJ6RLy5vG8SmQVpcdX0CGAvstMDAGOBw9LzkWmZtH5vSVre9zUzMzNQRHTPG0m9gEnA5sAlwA+BB9LRO5IGA7dHxLaSHic7TfBSWvcssEtEvNqqztHAaICmpqadxo0bV0isk6fPK6Sepj4w861CqmLYwHWKqaiiFixYQL9+/coOo0s8+dqThdU1oNcAZr87u5C6tll/m0LqqaI6f58AZr84v7C6evd9j0ULcx/3tWvAJmsVEE11VfE7NWLEiEkRMTzPtrnnxu+siHgX2EFSf+AGoK3Z91r2PNo6il9qryQixgBjAIYPHx7Nzc2FxHrc2bcWUs/pwxZxweRimnjqUc2F1FNVEyZMoKjfX9WcPPbkwuo6sd+JXLrg0kLqmnz45ELqqaI6f58ALvn8XYXVteHuC5l1f99O1zPqmObOB1NhPf071e7unKQfNjxvfS/7FRYRc4EJwK5Af0kt2XAQMCM9f4lsfABp/TrA60XFYGZmtjLpqO9mdMPzGzvzJpIGpCN6JPUB9gGeAv4EHJE2OxZouWXuzSyeue8I4K7orvMNZmZmNdNRH/Ojkq4FngRWl/SdtjaKiG/meJ+NgLHpvP0qwDURcYukJ4FxaZ79R4DL0vaXAVdKmkJ2RP/JfB/HzMzMWuso2R9BdnS/Kdk59MFtbJPraDsiHgM+1Eb5c8DObZS/TTZxj5mZmXVSu8k+ImYB50J23jwi2ps218zMzCos11DxiDhe0rpkt7MdCEwHbokID5ozMzOruFwXV0raDXgW+DywHfA5YEoqNzMzswrLexH4j4EvRMS/Zq2RdCRwEfDhrgjMzMzMipF32qQtgGtalV1LNhuemZmZVVjeZP8MS1/+Noqsa9/MzMwqLG83/mnALZJOAV4AhgBDgYO7KC4zMzMrSN7R+PdL+gBwELAx8DvgNo/GNzMzq77cd2mJiDnAr7owFjMzM+sCnb+voZmZmVWak72ZmVnNOdmbmZnVXO5kL2nTrgzEzMzMusbyHNk/ApAuvzMzM7MeosPR+JImAZPIEn2vVHwO2TS5ZmZm1gMs68j+COAOsnvarynpYWB1SSMkrdPl0ZmZmVmnLSvZrxIR10bE2cB8YCQg4GTgb5Ke6eoAzczMrHOWNanObyRtAjwJrAGsC7wdEf8OIGm9Lo7PzMzMOqnDZB8Ru0jqDQwD7gUuBtaSdCnwcHp4ylwzM7MKW+Zo/IhYFBGPAO9ExEeBhcAEshvhnN+14ZmZmVln5Z4bH/iv9DMi4mrg6i6Ix8zMzAqW+zr7iLg8Pd2sa0IxMzOzrrDc0+Wmu9+ZmZlZD+G58c3MzGrOyd7MzKzmnOzNzMxqzsnezMys5pzszczMaq5bkr2kwZL+JOkpSU9IOjWVryfpTknPpJ/rpnJJukjSFEmPSdqxO+I0MzOro+46sl8EnB4RWwO7AidJ2gY4GxgfEUOB8WkZ4ACyGfqGAqOBS7spTjMzs9rplmQfES9HxMPp+XzgKWAg2V30xqbNxgKHpecjgSsi8wDQX9JG3RGrmZlZ3SgiuvcNpSHAPcC2wIsR0b9h3ZyIWFfSLcB5EXFvKh8PnBURE1vVNZrsyJ+mpqadxo0bV0iMk6fPK6Sepj4w861CqmLYwHWKqaiiFixYQL9+/coOo0s8+dqThdU1oNcAZr87u5C6tll/m0LqqaI6f58AZr84v7C6evd9j0ULO3/cN2CTtQqIprqq+J0aMWLEpIgYnmfb5Zkbv9Mk9QOuA06LiDcktbtpG2VL7ZVExBhgDMDw4cOjubm5kDiPO/vWQuo5fdgiLphcTBNPPaq5kHqqasKECRT1+6uak8eeXFhdJ/Y7kUsXFHNWa/Lhkwupp4rq/H0CuOTzdxVW14a7L2TW/X07Xc+oY5o7H0yF9fTvVLeNxpe0Klmi/3VEXJ+KZ7Z0z6efs1L5S8DghpcPAmZ0V6xmZmZ10l2j8QVcBjwVEf/dsOpm4Nj0/FjgpobyY9Ko/F2BeRHxcnfEamZmVjfd1Y2/B3A0MFnS31LZV4HzgGsknQC8CIxK624DDgSmAG8Cx3dTnGZmZrXTLck+DbRr7wT93m1sH8BJXRqUmZnZSsIz6JmZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVXLcke0m/kDRL0uMNZetJulPSM+nnuqlcki6SNEXSY5J27I4YzczM6qq7juwvB/ZvVXY2MD4ihgLj0zLAAcDQ9BgNXNpNMZqZmdVStyT7iLgHeL1V8UhgbHo+FjisofyKyDwA9Je0UXfEaWZmVkeKiO55I2kIcEtEbJuW50ZE/4b1cyJiXUm3AOdFxL2pfDxwVkRMbKPO0WRH/zQ1Ne00bty4QmKdPH1eIfU09YGZbxVSFcMGrlNMRRW1YMEC+vXrV3YYXeLJ154srK4BvQYw+93ZhdS1zfrbFFJPFdX5+wQw+8X5hdXVu+97LFrY+eO+AZusVUA01VXF79SIESMmRcTwPNv27upgVoDaKGtzjyQixgBjAIYPHx7Nzc2FBHDc2bcWUs/pwxZxweRimnjqUc2F1FNVEyZMoKjfX9WcPPbkwuo6sd+JXLqgmDNbkw+fXEg9VVTn7xPAJZ+/q7C6Ntx9IbPu79vpekbpVZroAAAT00lEQVQd09z5YCqsp3+nyhyNP7Olez79nJXKXwIGN2w3CJjRzbGZmZnVRpnJ/mbg2PT8WOCmhvJj0qj8XYF5EfFyGQGamZnVQbd040u6CmgGNpD0EvAt4DzgGkknAC8Co9LmtwEHAlOAN4HjuyNGMzOzuuqWZB8Rn2pn1d5tbBvASV0bkZmZ2crDM+iZmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdVcFWfQs57inAKn8N3y23DOyM7Xc04xUx2bmdWJj+zNzMxqzkf2ZmZWWxcceXAh9Qza7zAuuPRHhdR1+tW3FFLP8vCRvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVnJO9mZlZzTnZm5mZ1ZyTvZmZWc052ZuZmdWcb3FrZpXx1FZbF1LP2yd/kac+f2IhdW399FOF1GNWJh/Zm5mZ1ZyTvZmZWc052ZuZmdWck72ZmVnNOdmbmZnVXGWTvaT9Jf1d0hRJZ5cdj5mZWU9VyWQvqRdwCXAAsA3wKUnblBuVmZlZz1TJZA/sDEyJiOci4h1gHDCy5JjMzMx6JEVE2TEsRdIRwP4R8Zm0fDSwS0R8sdV2o4HRaXFL4O/dGuiybQC8WnYQPYTbKh+3Uz5up/zcVvlUsZ02jYgBeTas6gx6aqNsqb2SiBgDjOn6cFaMpIkRMbzsOHoCt1U+bqd83E75ua3y6entVNVu/JeAwQ3Lg4AZJcViZmbWo1U12f8VGCrp/ZJWAz4J3FxyTGZmZj1SJbvxI2KRpC8CfwB6Ab+IiCdKDmtFVPYUQwW5rfJxO+XjdsrPbZVPj26nSg7QMzMzs+JUtRvfzMzMCuJkb2ZmVnNO9mZmZjXnZG9mtSBpjzxlZisjJ/sCSfo3Ses0LPeXdFiZMVWZpL6SVmlYXkXSmmXGVGWS+pYdQ8X9NGfZSk/SqDxllpHUR9KWZcfRGU72xfpWRMxrWYiIucC3Soyn6sYDjcl9TeCPJcVSWZJ2l/Qk8FRa3l7Sz0oOqzIk7SbpdGCApC81PM4hu3TXlvaVnGUrPUmHAH8Dfp+Wd5DU4+Z9qeR19j1YWztPbuP2rRERC1oWImKBj+zbdCGwH2liqYh4VNJHyw2pUlYD+pH9ra3VUP4GcEQpEVWUpAOAA4GBki5qWLU2sKicqCrvHLKbs00AiIi/SRpSXjgrxomoWBMl/TfZ7XkDOBmYVG5IlbZQ0o4R8TCApJ2At0qOqZIiYpq0xC0j3i0rlqqJiLuBuyVdHhEvlB1Pxc0g+590KEv+b5oP/FcpEVXfooiY1+rvr8dxsi/WycA3gKvJbuZzB3BSqRFV22nAbyW13PdgI+DIEuOpqmmSdgciTR99CqlL35bwpqQfAh8E1mgpjIi9ygupWiLiUeBRSb+KCB/J5/O4pP8AekkaSvb3d3/JMS03z6BnpZK0KtntiQU8HRH/LDmkypG0AfATYB8W70SeGhGvlRpYxUi6g2xH+8vA54FjgdkRcVapgVWIpMm0cQfRFhGxXTeG0yOkU4tfA/ZNRX8AvhsR/ygvquXnZF8AST+OiNMk/Y62b8V7aAlhVZakvSLiLkn/3tb6iLi+u2Oynk/SpIjYSdJjLUlL0t0R8bGyY6sKSZt2tN6nQZYmaVRE/HZZZVXnbvxiXJl+/qjUKHqOjwF3AYe0sS4AJ/sGkgYAnwWG0PA3GxH/WVZMFdXSK/SypIPIzk8PKjGeynEyXyFfAVon9rbKKs1H9gWStGFEzGpVtmVE/L2smKznk3Q/8GeyAVX/GpgXEdeVFlQFSTqYrJ0Gk11fvzbw7YjocZdJdTVJ81ncC7kasCqwMCLWLi+qamm4cuETZKeHWqwNbBMRO5cS2ArykX2x/izpGxFxDUC69vcEYJtyw6omSVcCX2yZmyB1Mf4iIvYuN7LKWdPnnZctIm5JT+cBI8qMpeoiovESRdLkXz0qeXWDGcBEanLlgo/sCyRpI7J7Hr8NNJGNmD698VpyW0zS58j+aL4EDATOIGuv35UaWMVIOhe4PyJuKzuWKpO0BXAp0BQR20raDjg0Is4tObQeQdIDEbFr2XFUjaRV6zBw2Mm+YJJOIjuf8x7wqYi4r+SQKk3SnsCfgFeBD0XEKyWHVDmpy7Uv8E56CAh3uS5J0t1kO4w/j4gPpbLHI2LbciOrnlaDY1cBhgMfi4jdSgqpstLldt8n66FtvKRzs9KCWgHuxi+QpDuBl4FtyQYG/ULSPRHx5XIjqyZJR5PNS3AMsB1wm6Tj07XAlrTucrV2rRkRD7Wa/MTXkretcXDsImAqMLKcUCrvl2TTnl9IdnroeLId7h7Fyb5Yl0TEjen53DQRiuebbt/hwJ5pUONVkm4ALgc+VGpUFaMsex0FvD8ivitpMLBRRDxUcmhV86qkD5AGnkk6gmzn21qJiOPLjqEH6RMR4yUpXc1wjqQ/08Pue+Ju/IJJagI+nBYfaj063zomabWIeKfsOKpE0qVkp4X2ioitJa0L3BERH17GS1cqkjYjGzOzOzAHeB44ypebLU3SD4Bzyaan/j2wPXBaRPyq1MAqSNJ9wEeAa8kuGZ4OnBcRPeoueL7rXYEkfQJ4CBhFdrnGg+nowtogaZCkGyTNljRT0nXAhmXHVUG7RMRJZAM/iYg5ZJdLWZJulTw8IvYBBgBbRcSeTvTt2jci3gAOBl4CtiAb72BLO43sjpynADsBR5PNztijuBu/WF8DPtxyNJ8mQ/kj2R6hLe2XwG/Ido4APp3KPl5aRNX0T0m9WNw9PYDsSN+SiHhP0heBayJiYdnx9ACrpp8HAldFxOs9/UYvXSUi/pqeLiA7X98jOdkXa5VW3fav4d6TjgyIiF82LF8u6bTSoqmui4AbgA0lfY/stq1fLzekSrpT0pfJJkD5V8KPiNfLC6myfifpabJu/C+kHci3S46pktIlnWcAm7LkDJY96gZLPmdfoHQebHvgqlR0JPCYJ0Rpm6Q/kg3Ia2mvTwHHe1KdpUnaCtibbBTw+IjwXe9akfR8G8XR0y6R6i5p7McbEfFuutnL2r70dWmSHgX+h6VnsOxRty93si+QpPOBB4E9yf4p3wPs6mTfNkmbABcDu5F1Ud8PnBIRL5YaWMVI2hV4IiLmp+W1yKbrfLDcyKwnS1cLDWHJo9UrSguoolpusFR2HJ3lZF8gSQ9HxI6tyv51By5bkqQ9Wk861FbZyk7SI8COkf5Y02C0ia2/a+YElleaqvoDwN9YfLQaEXFKeVFVi6T10tNTgFlkp9L+dVvbnnZ6yOfsCyDpROALwGaSHmtYtRbgxNW+nwKtE1ZbZSs7RcNeeRqM5r/dVtpLYICT/dKGk/UO+WivfZPIvj8tIxcbr1YIoEedHvI/jGL8BridbErFsxvK5/e0vb/uIGk3smuhB0j6UsOqtYFe5URVac9JOoVs3nfIdiyfKzGeqnICy+9x4H140qF2RcT782wn6eMRcWdXx9NZTvYFSHdtm0c2wMyWbTWgH9n3r3Eq2DfIRprbkj5PNiL/62RHFOOB0aVGVE1OYPltADwp6SGW7Jo+tLyQeqzzgcone5+zt9JI2rSjSU8k/TQiTu7OmKznkfQ7sp2gtYAdyCa2cgLrgKSPtVUeEXd3dyw9naRHWm68VGU+srfS5JjdbI9uCaTiPLXpMv2I7Lzq+cBhDeUtZdaKk3qhesQRs5O9WfXtGxFnSvo3sqlNR5HdFtjJnsWJK913fIkkJqlPOVFVk6R7I2LPdNvkxiTl2ybXnJO9WfV5atMO+GqY/CJiz/TTt00uztSyA8jDyd6qzBkt46lNO+arYazLSJpIuo9HugnVEiLi37s/quXnAXpWOkl927p5iaTjIuLyEkKqHE9talYOSZuT3QDnSKAl8d/R0y7xdLK30qTZzv4X6BcRm0jaHvhcRHyh5NAqRdIaZN3Ue5KdZ70XuDQifHRv1k3SzJUHk8138R7wC+AnPaX3yHdkszJdCOxHdndAIuJR4KOlRlRNVwAfJJtd8GJga+DKUiMyW4lI2g64APghcB3ZfCBvAHeVGdfy8Dl7K1VETGs12Ozd9rZdiW0ZEds3LP8p3YnLzLqYpEnAXOAy4OyIaJnD4UFJPebyYCd7K9O01JUfklYju+GEb926tEck7RoRDwBI2gWPMjfrLqMiYonpqSW9PyKe7ymD88Dn7K1EkjYAfgLsQzby/g7g1Ih4rdTAKkLSZLJz9KsCWwIvpuVNgScjYtsSwzNbKbRzN9Med9tbH9lbKST1Ao6OiKPKjqXCDm54vi7wkfT8HrJuRTPrIpK2Ihsrs46kxiP4tYE1yolqxXmAnpUiIt4FRpYdR5VFxAtpSuHDyAbkbQAMSM8937tZ19qSbIe7P3BIw2NH4LMlxrVC3I1vpZH0PWAd4GrgX9fZR8TDpQVVQWlWuN1a5iKQ1Bf4S0RsV25kZvUnabeI+EvZcXSWu/GtTLunn99pKAtgrxJiqTKx5FUK7+LZBc26lKQzI+IHwH9IWur25RFxSglhrTAneytNRIwoO4Ye4pdkl/nckJYPI7sMyMy6TsuVQRNLjaIg7sa30khqAv4/YOOIOEDSNmTd1U5krUjakWwGPQH3RMQjJYdktlKQNCoifrussqpzsrfSSLqd7Kj1axGxvaTewCMRMazk0MzMgHYvvVuqrOrcjW9l2iAirpH0FYCIWCTJM+iZWekkHUB2W+mBki5qWLU2sKicqFack72VaaGk9ckG5SFpV2BeuSGZmQEwg+x8/aHApIby+cB/lRJRJ7gb30ojaSfgImBb4HGya8iPiIjHSg3MzCyRtGpE/LPsODrLyd5Klc7Tb0k28OzvdfijMrP6SDe7OYdsmureZP+rIiI2KzOu5eVkb6VJd267Grg6Ip4tOx4zs9YkPU3WbT+Jhvkueto9PJzsrTSSNgWOTI/3yBL/NRHxYqmBmZklkh6MiF3KjqOznOytEiQNBb4BHBURvcqOx8wMQNJ5QC/geqDlXvY9blpvj8a3UkkaAnyC7Oj+XeDMMuMxM2ul5ah+eENZj5vW20f2VhpJD5Ldq/23ZOftnys5JDOzWnKyt9JI2ioini47DjOz9tRlWm/fz97KNEfSZWnaXCRtI+mEsoMyM2twOfAHYOO0/H/AaaVFs4Kc7K1Ml1ODPyIzq7UNIuIasiuGiIhFLHnL6R7Byd7KVIs/IjOrtVpM6+3R+FamWvwRmVmtfQm4GfiApPtI03qXG9Ly8wA9K026R/tP8dz4ZlZhdZjW20f2VqYPAAcAg4HDya5n9XfSzEon6d/bWbWFJCLi+m4NqJP8j9XK9I2I+K2kdYF9gAuAS1k8iYWZWVkOST83BHYH7krLI4AJZDPq9RgeoGdlahmMdxDwPxFxE7BaifGYmQEQEcdHxPFkY4q2iYjDI+Jw4IMlh7ZCnOytTNMl/ZxsutzbJK2Ov5NmVi1DIuLlhuWZwBZlBbOiPEDPSiNpTWB/YHJEPCNpI2BYRNxRcmhmZgBIuhgYClxFdpT/SWBKRJxcamDLycnezMysA2mw3kfS4j0RcUOZ8awIJ3szM7Oa82h8MzOzViTdGxF7SppPmvirZRUQEbF2SaGtEB/Zm5mZ1ZxHPpuZmdWck72ZmVnNOdmbmZnVnJO9mS1B0lRJ+5Qdh5kVx8nezCoh3VnMzLqAk71ZjUkaLOl6SbMlvSbpYkkfkHRXWn5V0q8l9U/bXwlsAvxO0gJJZ6byXSXdL2mupEclNTe8x/sl3SNpvqQ/SrpE0q8a1h8q6Yn02gmStm5YN1XSWZIeAxZKOkPSda0+w08l/bhrW8qs3pzszWpKUi/gFuAFYAgwEBhHdp3w94GNga3JbjF8DkBEHA28CBwSEf0i4geSBgK3AucC6wFfBq6TNCC91W+Ah4D1Uz1HN8SwBdk0o6cBA4DbyHYkGm949CmymyH1B34F7N+w89EbOBK4sphWMVs5Odmb1dfOZAn9jIhYGBFvR8S9ETElIu6MiH9ExGzgv4GPdVDPp4HbIuK2iHgvIu4EJgIHStoE+DDwzYh4JyLuBW5ueO2RwK3p/f4J/AjoQ3bL0BYXRcS0iHgr3XDkHmBUWrc/8GpETOp0a5itxJzszeprMPBCRCxqLJS0oaRxkqZLeoPsaHqDDurZFBiVuuHnSpoL7AlsRLYz8XpEvNmw/bSG5xuT9SwAEBHvpfUD29keYCzZDgbpp4/qzTrJyd6svqYBm7Qx8O37ZNN/bpem/Pw0Wdd+i9bTak4DroyI/g2PvhFxHvAysF66g2GLwQ3PZ5DtLAAgSWn99A7e70ZgO0nbAgcDv87xWc2sA072ZvX1EFkyPk9SX0lrSNoDWAtYAMxN5+PPaPW6mcBmDcu/Ag6RtJ+kXqmeZkmDIuIFsi79cyStJmk34JCG114DHCRpb0mrAqcD/wDuby/oiHgbuJY0FiAiXuxEG5gZTvZmtRUR75Il3s3JBt29RHYO/dvAjsA8soF317d66feBr6cu+y9HxDRgJPBVYDbZkf4ZLP7/cRSwG/Aa2SC+q8kSOhHxd7Keg58Cr6Z4DomId5YR/lhgGO7CNyuEb4RjZoWSdDXwdER8qxN1bAI8DbwvIt4oLDizlZSP7M2sUyR9OF27v4qk/cl6AW7sRH2rAF8CxjnRmxXDM1aZWWe9j+xUwPpkpwpOjIhHVqQiSX3Jxgy8QHbZnZkVwN34ZmZmNedufDMzs5pzsjczM6s5J3szM7Oac7I3MzOrOSd7MzOzmvt/9xhtWjtufN0AAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 576x360 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "df_stats.plot(x='category', y='number_of_comments', kind='bar', legend=False, grid=True, figsize=(8, 5))\n",
    "plt.title(\"Number of comments per category\")\n",
    "plt.ylabel('# of Occurrences', fontsize=12)\n",
    "plt.xlabel('category', fontsize=12)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 0, '# of categories')"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAgEAAAFQCAYAAAAm3K2uAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvOIA7rQAAIABJREFUeJzt3Xm4JVV57/Hvj0FkEAFpkBkVQpzi1CKGOIEBHBCvVyJGI+GSkNzrmGvirChqruYmcbgOCQGkcQgiRkFDVIKzhqFB1DAYWga7AaGxG0QIIPjeP2qduDmec3o3nr0359T38zz72VWrVtV6a5+G/e61VlWlqpAkSf2zwaQDkCRJk2ESIElST5kESJLUUyYBkiT1lEmAJEk9ZRIgSVJPmQRIs0hSSfaYY/tFSZ465LGuTPL0eQvuXi7Jk5L8YNJxSJqbSYAWnfaFe0eSbaeVX9i+2He/B8c8Mck7Bsuq6uFV9dVfK9gRSfLUJKsm1X5VfaOq9ppU+4Iku7d/7xtNOhbde5kEaLG6Anjh1EqSRwKbTi6c/lgIXzoLIUZpHEwCtFh9FHjJwPrhwEmDFZJ8NckfDaz/YZJvTj9QkqOAFwGvSfKzJJ9r5f/VxZ/krUlOTfLJJDcnuSDJo2YKLMkGSV6X5IdJfpLklCTbzHYiSQ5pvRg/bfsc1MqPSHJJa+/yJH/SyjcH/gXYscX7syQ7rqvdJC9JclXb9uZp57dJkvcmuaa93ptkk7btqUlWJXltkh8DH5neE9Ha/3SS1UmuSPKKgW17J1nezu+6JH87y+cw1c4bktzQ4nvRwPZNkvx1kh+14/xdkk1ni3GWNv544DO9OMljW/lD27+XG9sw0HMG9jkxyYeS/Ev7rL+V5IHtM1qb5NIkjxmof2WSv0jyvSS3JDk+yfZt/5uT/GuSrQfq75Pk263t72ZgCKrF9PbW5s1JvpRf9oB9vb3f2OJ64kznrH4zCdBidTawZfuf94bAC4CP3ZMDVdWxwMeBv6qqLarq4FmqHgJ8CtgG+ATw2SQbz1DvFcBzgacAOwJrgQ/OdMAke9MlL38BbAU8Gbiybb4eeDawJXAE8J4kj62qW4BnANe0eLeoqmvmajfJw4AP0SU7OwD3B3YaCOWNwD7Ao4FHAXsDbxrY/sB23rsBR007hw2AzwHfbcfcH3hVkgNblfcB76uqLYGHAKfM9FkMtLNtO87hwLFJpoYd3g38Rotxj1bnLcPE2OI8FHgrXfK4JfAc4Cftb/g54EvAdsDLgY8PtAvwe+3z2Ba4Hfg34IK2fiowPbH578DvtngPpkva3tDqb0D3tyLJTsA/A+9osf858OkkSwaO9ft0f//tgPu0OtD9WwHYqv0b+Lfp5yyZBGgxm+oN+F3gUuDqEbd3flWdWlU/p/uf/n3pvjin+xPgjVW1qqpup/vieX5m7qI+Ejihqs6sql9U1dVVdSlAVf1zVf2wOl+j+5J60hzxzdXu84HPVdU3q+oOui/PwQeLvAg4pqqur6rVwNuAPxjY/gvg6Kq6var+c1q7jweWVNUxVXVHVV0O/ANwWNv+c2CPJNtW1c+q6uw5zgHgza2dr9F9Qf5ekgB/DPxZVa2pqpuBvxxoY10xAvwRXaJ3XvtMV1TVVXR/wy2Ad7X4vwx8noHhJuAzVXV+Vd0GfAa4rapOqqq7gE8Cj5nW1v+rquuq6mrgG8A5VfWd9nf5zED9FwNnVNUZ7e9/JrAceObAsT5SVf/RzukUuiRIGorjYlrMPkrXJfogpg0FjMjKqYWq+kXrDt9xhnq7AZ9J8ouBsruA7fnVRGUX4IyZGkvyDOBoul+TGwCbAd+fI7652t1xWvy3JvnJQL0dgasG1q/i7ue2un0BztbujkluHCjbkO7LD7pE5xjg0iRXAG+rqs/Pcqy1radjehxL6M7//C4fACCtnWFihO6z/uEM5TsCK6tq8HO7irv3lFw3sPyfM6xvMe2Yw9bfDTg0yWDv08bAVwbWfzywfOsMbUmzMgnQolVVV7UvlWfSfdFMdwvdF8eUB851uCGa3GVqoXWB7wxcM0O9lcD/qKpvDXHMlXRd5HfTxuM/TdfTcVpV/TzJZ+m++GaLd9Z2k1wL7DWwvinwgIEq19B9IV3U1nfl7uc21+ezEriiqvacaWNVXQa8sH1mzwNOTfKAaV/2U7ZOsvnAtl2BfwduoPvyfHj7dT1jU3PEOBXnr3zWdOe5S5INBhKBXYH/WMfx5sNK4KNV9cf3YF8fEat1cjhAi92RwH6zfKFcCDwvyWbp7gcwU6Iw5Trgweto63FJnte6119FNzY8U9f23wHvTLIbQJIlSQ6Z5ZjHA0ck2T/dxL6dkvwm3djvJsBq4M7WK3DAtHgfkOT+Q7Z7KnBwkt9Och+67v4M7PuPwJvaPtvSDRcMO8fiXOCnbVLepkk2TPKIJI9vcbw4yZL2BTvVW3DXHMd7W5L7JHkS3ZyIT7V9/4FuXsR27bg7Dcw7GMZxwJ8neVw6e7TP6hy6hPE1STZuE/MOBk5ej2PfUx+j+7sc2D63+6ab5LjzEPuuphsCWde/W/WYSYAWtTZmvnyWze8B7qD7wlxGN/lvNscDD2sztD87S53T6CYgrqUbL39emx8w3fuA04EvJbmZLlF4wizxn0ub9AfcBHwN2K2Neb+Cbgx4Ld3ksNMH9ruU7ov78hbzjnO1W1UX0U14Oxm4FriZbuLh7e2Q76Abi/4e3ZDDBa1sndq4+MF0Y9VX0P1qP45u8iHAQcBFSX7WYjxsjm77H7fzvYbu7/WnU3MkgNcCK4Czk/wU+FcGejeGiPNTwDvpJnXeDHwW2KbNkXgO3WTLG+gmUL5koN2RqaqVdBNO30D3pb6SbpLoOv/fXVW30p3Pt9q/gZnmp6jnUmWPkfTrSvJWYI+qevGkY5kPSbag+1W+Z1VdMel4oLvMD/hYVQ3zK1jSEOwJkARAkoPb0MjmwF/T/eK/crJRSRolkwBJUw6h62a/BtiTrlverkJpEXM4QJKknrInQJKknjIJkCSppxb9zYK23Xbb2n333ScdhiRJY3P++effUFVL1lVv0ScBu+++O8uXz3aZuCRJi0+Sq9Zdy+EASZJ6yyRAkqSeMgmQJKmnTAIkSeopkwBJknrKJECSpJ4yCZAkqadMAiRJ6imTAEmSesokQJKknjIJkCSppxb9swPm8ri/OGnSIcyb8//vSyYdgiRpgbEnQJKknjIJkCSpp0wCJEnqKZMASZJ6yiRAkqSeMgmQJKmnTAIkSeopkwBJknpqbElAkq2SnJrk0iSXJHlikm2SnJnksva+daubJO9PsiLJ95I8duA4h7f6lyU5fFzxS5K02IyzJ+B9wBeq6jeBRwGXAK8DzqqqPYGz2jrAM4A92+so4MMASbYBjgaeAOwNHD2VOEiSpPUzliQgyZbAk4HjAarqjqq6ETgEWNaqLQOe25YPAU6qztnAVkl2AA4EzqyqNVW1FjgTOGgc5yBJ0mIzrp6ABwOrgY8k+U6S45JsDmxfVdcCtPftWv2dgJUD+69qZbOVS5Kk9TSuJGAj4LHAh6vqMcAt/LLrfyaZoazmKL/7zslRSZYnWb569ep7Eq8kSYveuJKAVcCqqjqnrZ9KlxRc17r5ae/XD9TfZWD/nYFr5ii/m6o6tqqWVtXSJUuWzOuJSJK0WIwlCaiqHwMrk+zVivYHLgZOB6Zm+B8OnNaWTwde0q4S2Ae4qQ0XfBE4IMnWbULgAa1MkiStp43G2NbLgY8nuQ9wOXAEXRJySpIjgR8Bh7a6ZwDPBFYAt7a6VNWaJG8Hzmv1jqmqNeM7BUmSFo+xJQFVdSGwdIZN+89Qt4CXznKcE4AT5jc6SZL6xzsGSpLUUyYBkiT1lEmAJEk9ZRIgSVJPmQRIktRTJgGSJPWUSYAkST1lEiBJUk+ZBEiS1FMmAZIk9ZRJgCRJPWUSIElST5kESJLUUyYBkiT1lEmAJEk9ZRIgSVJPmQRIktRTJgGSJPWUSYAkST1lEiBJUk+ZBEiS1FMmAZIk9ZRJgCRJPWUSIElST5kESJLUUyYBkiT1lEmAJEk9ZRIgSVJPmQRIktRTJgGSJPWUSYAkST1lEiBJUk+NLQlIcmWS7ye5MMnyVrZNkjOTXNbet27lSfL+JCuSfC/JYweOc3irf1mSw8cVvyRJi824ewKeVlWPrqqlbf11wFlVtSdwVlsHeAawZ3sdBXwYuqQBOBp4ArA3cPRU4iBJktbPpIcDDgGWteVlwHMHyk+qztnAVkl2AA4EzqyqNVW1FjgTOGjcQUuStBiMMwko4EtJzk9yVCvbvqquBWjv27XynYCVA/uuamWzlUuSpPW00Rjb2reqrkmyHXBmkkvnqJsZymqO8rvv3CUZRwHsuuuu9yRWSZIWvbH1BFTVNe39euAzdGP617Vuftr79a36KmCXgd13Bq6Zo3x6W8dW1dKqWrpkyZL5PhVJkhaFsSQBSTZPcr+pZeAA4N+B04GpGf6HA6e15dOBl7SrBPYBbmrDBV8EDkiydZsQeEArkyRJ62lcwwHbA59JMtXmJ6rqC0nOA05JciTwI+DQVv8M4JnACuBW4AiAqlqT5O3Aea3eMVW1ZkznIEnSojKWJKCqLgceNUP5T4D9Zygv4KWzHOsE4IT5jlGSpL6Z9CWCkiRpQkwCJEnqKZMASZJ6yiRAkqSeMgmQJKmnTAIkSeopkwBJknrKJECSpJ4yCZAkqadMAiRJ6imTAEmSesokQJKknjIJkCSpp4ZKApK8MMlD2/JeSb6e5MtJfnO04UmSpFEZtifgHcCatvzXwLnA14EPjSIoSZI0ehsNWW9JVV2X5L7A7wDPB34O3DCyyCRJ0kgNmwSsTrIH8EjgvKq6PclmQEYXmiRJGqVhk4C3A+cDdwEvaGX7A98dRVCSJGn0hkoCqurEJKe05Vtb8TnAYaMKTJIkjdb6XCK4KfDfk7ymrW/E8D0JkiTpXmbYSwSfAvwAeBHw5la8J/DhEcUlSZJGbNiegPcCL6iqg4A7W9k5wN4jiUqSJI3csEnA7lV1Vluu9n4HDgdIkrRgDZsEXJzkwGllTwe+P8/xSJKkMRn2l/yrgc8n+Wdg0yR/DxwMHDKyyCRJ0kgN1RNQVWcDvwVcBJwAXAHsXVXnjTA2SZI0QkP1BCTZBFhdVX81ULZxkk2q6vaRRSdJkkZm2DkBZwKPm1b2OOCL8xuOJEkal2GTgEfSXRI46FzgUfMbjiRJGpdhk4CbgO2nlW0P3DK/4UiSpHEZNgn4NPCJJI9IslmSRwInAaeMLjRJkjRKwyYBbwQuoRsCuBk4m+42wm8YUVySJGnEhr1E8LaqeimwOfBAYIuqellV3bY+jSXZMMl3kny+rT8oyTlJLkvyyST3aeWbtPUVbfvuA8d4fSv/wQw3MJIkSUMa+imCSe4PPJ5ukuDTkuyXZL/1bO+VdD0KU94NvKeq9gTWAke28iOBtVW1B/CeVo8kD6N7fPHDgYOADyXZcD1jkCRJDP8UwT8ErgE+Bxw/8Dpu2IaS7Aw8a2qfJAH2A05tVZYBz23Lh7R12vb9W/1DgJOr6vaqugJYgQ8xkiTpHhn2tsHvBJ5fVf/ya7T1XuA1wP3a+gOAG6tq6qmEq4Cd2vJOwEqAqrozyU2t/k508xGYYR9JkrQehh0O2Aj40j1tJMmzgeur6vzB4hmq1jq2zbXPYHtHJVmeZPnq1avXO15Jkvpg2CTg3cCbkgw9h2CafYHnJLkSOJluGOC9wFZJpnojdqYbcoDuF/4uAG37/YE1g+Uz7PNfqurYqlpaVUuXLFlyD0OWJGlxG/ZL/c+ANwE3J/nR4GuYnavq9VW1c1XtTjex78tV9SLgK8DzW7XDgdPa8ultnbb9y1VVrfywdvXAg4A96S5blCRJ62nYOQEvHlH7rwVOTvIO4Dt0kw1p7x9NsoKuB+AwgKq6KMkpwMXAncBLq+quEcUmSdKiNlQSUFVfm68Gq+qrwFfb8uXMMLu/3X/g0Fn2fyfdREVJkvRrGPYSwU2SvDPJ5W2mPkkOSPKy0YYnSZJGZdg5Ae8BHgG8iF/Oxr8I+J+jCEqSJI3esHMC/huwR1XdkuQXAFV1dRKv0ZckaYEatifgDqYlDEmWAD+Z94gkSdJYDJsEfApY1i7LI8kOwAforvmXJEkL0LBJwBuAK4HvA1sBl9HdpOdtowlLkiSN2jrnBLS7BP4O8NqqelUbBrih3bxHkiQtUOvsCaiqXwCnVdXtbX21CYAkSQvfsMMBX0+yz0gjkSRJYzXsJYJXAf+S5DS6R/z+V09AVb1lFIFJkqTRGjYJ2BT4bFveeaDcYQFJkhaoYScGfhT41tS8AEmStPCt98RASZK0ODgxUJKknnJioCRJPfXrTgyUJEkL1FBJQFUdMepAJEnSeA2VBCR58Gzbqury+QtHkiSNy7DDASvo5gFkoGxqXsCG8xqRJEkai2GHA+52FUGSBwJHA98YRVCSJGn0hr1E8G6q6sfAq4D/M7/hSJKkcblHSUCzF7DZfAUiSZLGa9iJgd/g7s8J2Ax4OHDMKIKSJEmjN+zEwOOmrd8CfLeqLpvneCRJ0pgMOzFw2agDkSRJ4zXUnIAk/5TkSdPKnpTk1NGEJUmSRm3YiYFPAb49rezfgKfNbziSJGlchk0CbgM2n1a2BfDz+Q1HkiSNy7BJwBeBv0+yJUB7/wDwhVEFJkmSRmvYJODVwJbAmiTXA2uA+9PdMEiSJC1Aw14dsBZ4Vrtd8C7AynbXQEmStEANe7OgA4Arq+o/gB+3sr2AXavqzBHGJ0mSRmTY4YAPAjdPK7u5la9TkvsmOTfJd5NclORtrfxBSc5JclmSTya5TyvfpK2vaNt3HzjW61v5D5IcOGT8kiRpmmGTgO2q6tppZdcCDxxy/9uB/arqUcCjgYOS7AO8G3hPVe0JrAWObPWPBNZW1R7Ae1o9kjwMOIzulsUHAR9K4qOMJUm6B4ZNAi5Pst+0sqcCVwyzc3V+1lY3bq8C9gOmbji0DHhuWz6krdO2758krfzkqrq9qq4AVgB7D3kOkiRpwLDPDngr8E9Jjgd+CDwEOKK9htJ+sZ8P7EE3jPBD4MaqurNVWQXs1JZ3AlYCVNWdSW4CHtDKzx447OA+kiRpPQzVE1BVpwEH0N0w6Fnt/cBWPpSququqHg3sTPfr/aEzVWvvmWXbbOV3k+SoJMuTLF+9evWwIUqS1CvD9gRQVecC5/66DVbVjUm+CuwDbJVko9YbsDNwTau2iu5SxFVJNqK7J8GagfIpg/sMtnEscCzA0qVLfyVJkCRJQ/QEJNk9yYlJrk5ye3tfluTBwzaSZEmSrdrypsDTgUuArwDPb9UOB6Z6Fk5v67TtX66qauWHtasHHgTsyTwkJpIk9dGcPQFJHgp8i24c/o10VwTsAPwesDzJvlV1yRDt7AAsa/MCNgBOqarPJ7kYODnJO4DvAMe3+scDH02ygq4H4DCAqrooySnAxcCdwEur6q71OmNJkgSsezjgXcAHq+rN08pPbF/cfwUcvK5Gqup7wGNmKL+cGWb3V9VtwKGzHOudwDvX1aYkSZrbupKAJ/PLbvnp/oYhLxGUJEn3PuuaE7Ahsz8u+OdtuyRJWoDWlQScx+z3AvhDYPm8RiNJksZmXcMBbwa+2B4WdCq/nBh4KN0wgffulyRpgZqzJ6Cqvk13k6BHAWcBl7b3RwEHte2SJGkBWufNgqrq34Ant+v7t6F7sM+tI49MkiSN1PrcMfA/gatHGIskSRqjYZ8iKEmSFhmTAEmSemrWJCDJ/x1Y3m884UiSpHGZqyfgqIHlz446EEmSNF5zTQz8bpJT6R7Ws0mSY2aqVFVvGUlkkiRppOZKAp5P1xuwGxBglxnq1CiCkiRJozdrElBV1wPvAEiyUVXNdvtgSZK0AA11n4CqOiLJ1nSPDd6J7n4Bn6+qNaMMTpIkjc5QlwgmeSLwQ+BPgd8C/gRY0colSdICNOwdA98L/K+qOnmqIMkLgPcDjx9FYJIkabSGvVnQbwCnTCs7FdhjfsORJEnjMmwScBlw2LSyQ+mGCCRJ0gI07HDAq4DPJ3kFcBWwO7An8OwRxSVJkkZs2KsDvp3kIcCzgB2BzwFneHWAJEkL1/o8Sngt8LERxiJJksbIpwhKktRTJgGSJPWUSYAkST01dBKQZLdRBiJJksZrfXoCvgPQLhOUJEkL3JxXByQ5HzifLgHYsBW/le52wZIkaQFbV0/A84EvAbsBmyW5ANgkydOS3H/k0UmSpJFZVxKwQVWdWlWvA24GDgECvBy4MMllow5QkiSNxrpuFvSJJLsCFwP3BbYGbquq5wEk2WbE8UmSpBGZMwmoqick2Qh4JPBN4APA/ZJ8GLigvbx1sCRJC9A6rw6oqjur6jvAHVX1ZOAW4Kt0DxB69zCNJNklyVeSXJLkoiSvbOXbJDkzyWXtfetWniTvT7IiyfeSPHbgWIe3+pclOXz9T1mSJMH6XSL4Z+29quqTVfWaqnr6kPveCby6qh4K7AO8NMnDgNcBZ1XVnsBZbR3gGXRJxp7AUcCH4b+GH44GngDsDRw9lThIkqT1M3QSUFUntsUHr28jVXVtVV3Qlm8GLgF2optouKxVWwY8ty0fApxUnbOBrZLsABwInFlVa9oDjc4EDlrfeCRJ0j24bXD78r3HkuwOPAY4B9i+qq5tx70W2K5V2wlYObDbqlY2W7kkSVpPY312QJItgE8Dr6qqn85VdYaymqN8ejtHJVmeZPnq1avvWbCSJC1yY0sCkmxMlwB8vKr+qRVf17r5ae/Xt/JVwC4Du+8MXDNH+d1U1bFVtbSqli5ZsmR+T0SSpEViLElAkgDHA5dU1d8ObDodmJrhfzhw2kD5S9pVAvsAN7Xhgi8CByTZuk0IPKCVSZKk9bSumwXNl32BPwC+n+TCVvYG4F3AKUmOBH4EHNq2nQE8E1gB3AocAVBVa5K8HTiv1TumqrxPgSRJ98BYkoCq+iYzj+cD7D9D/QJeOsuxTgBOmL/oJEnqp7FODJQkSfceJgGSJPWUSYAkST1lEiBJUk+ZBEiS1FMmAZIk9ZRJgCRJPWUSIElST5kESJLUUyYBkiT1lEmAJEk9ZRIgSVJPmQRIktRTJgGSJPWUSYAkST1lEiBJUk+ZBEiS1FMmAZIk9ZRJgCRJPWUSIElST5kESJLUUyYBkiT1lEmAJEk9ZRIgSVJPmQRIktRTJgGSJPWUSYAkST1lEiBJUk+ZBEiS1FMmAZIk9ZRJgCRJPWUSIElST40lCUhyQpLrk/z7QNk2Sc5Mcll737qVJ8n7k6xI8r0kjx3Y5/BW/7Ikh48jdkmSFqtx9QScCBw0rex1wFlVtSdwVlsHeAawZ3sdBXwYuqQBOBp4ArA3cPRU4iBJktbfWJKAqvo6sGZa8SHAsra8DHjuQPlJ1Tkb2CrJDsCBwJlVtaaq1gJn8quJhSRJGtIk5wRsX1XXArT37Vr5TsDKgXqrWtls5ZIk6R64N04MzAxlNUf5rx4gOSrJ8iTLV69ePa/BSZK0WEwyCbiudfPT3q9v5auAXQbq7QxcM0f5r6iqY6tqaVUtXbJkybwHLknSYjDJJOB0YGqG/+HAaQPlL2lXCewD3NSGC74IHJBk6zYh8IBWJkmS7oGNxtFIkn8Engpsm2QV3Sz/dwGnJDkS+BFwaKt+BvBMYAVwK3AEQFWtSfJ24LxW75iqmj7ZUJIkDWksSUBVvXCWTfvPULeAl85ynBOAE+YxNEmSeuveODFQkiSNgUmAJEk9ZRIgSVJPmQRIktRTJgGSJPWUSYAkST1lEiBJUk+ZBEiS1FMmAZIk9ZRJgCRJPWUSIElST5kESJLUUyYBkiT1lEmAJEk9ZRIgSVJPmQRIktRTJgGSJPWUSYAkST1lEiBJUk+ZBEiS1FMmAZIk9ZRJgCRJPWUSIElST5kESJLUUxtNOgBNxo+OeeSkQ5g3u77l+5MOQZIWJHsCJEnqKZMASZJ6yiRAkqSeck6A1ENfe/JTJh3CvHnK17826RCkBcskQL207//bd9IhzJtvvfxbkw5B0gLlcIAkST1lEiBJUk8tyOGAJAcB7wM2BI6rqndNOCRJC8gHXv25SYcwb172NwdPOgQtYAuuJyDJhsAHgWcADwNemORhk41KkqSFZ8ElAcDewIqquryq7gBOBg6ZcEySJC04C3E4YCdg5cD6KuAJE4pFkhacd774+ZMOYd688WOnTjqEBS1VNekY1kuSQ4EDq+qP2vofAHtX1csH6hwFHNVW9wJ+MPZAf2lb4IYJtj9pnr/n39fz7/O5g+c/6fPfraqWrKvSQuwJWAXsMrC+M3DNYIWqOhY4dpxBzSbJ8qpaOuk4JsXz9/z7ev59Pnfw/BfK+S/EOQHnAXsmeVCS+wCHAadPOCZJkhacBdcTUFV3JnkZ8EW6SwRPqKqLJhyWJEkLzoJLAgCq6gzgjEnHMaR7xbDEBHn+/dbn8+/zuYPnvyDOf8FNDJQkSfNjIc4JkCRJ88AkYISSHJTkB0lWJHndpOMZpyQnJLk+yb9POpZxS7JLkq8kuSTJRUleOemYxinJfZOcm+S77fzfNumYJiHJhkm+k+Tzk45l3JJcmeT7SS5MsnzS8YxTkq2SnJrk0vb/gCdOOqa5OBwwIu32xv8B/C7dZY3nAS+sqosnGtiYJHky8DPgpKp6xKTjGackOwA7VNUFSe4HnA88t0d/+wCbV9XPkmwMfBN4ZVWdPeHQxirJ/waWAltW1bMnHc84JbkSWFpVvbtPQJJlwDeq6rh2BdtmVXXjpOOajT0Bo9Pr2xtX1deBNZOOYxKq6tqquqAt3wxcQneny16ozs/a6sbt1atfG0l2Bp4FHDfpWDQ+SbYEngwcD1BVd9ybEwAwCRilmW5v3JsvAnWS7A48BjhnspGMV+sKvxC4Hjizqnp1/sB7gdcAv5h0IBNSwJeSnN/u4NoXDwZWAx9pQ0HHJdl80kHNxSRgdDJDWa9+DfVdki2ATwOvqqqfTjqecaqqu6rq0XR39Nw7SW+GhJI8G7i+qs6fdCwTtG9VPZbuaa8vbcODfbAR8Fjgw1X1GOAW4F49H8wkYHTWeXtjLV5tLPzTwMer6p9gamyOAAAF40lEQVQmHc+ktK7QrwIHTTiUcdoXeE4bFz8Z2C/JxyYb0nhV1TXt/XrgM3TDo32wClg10PN1Kl1ScK9lEjA63t64p9rEuOOBS6rqbycdz7glWZJkq7a8KfB04NLJRjU+VfX6qtq5qnan++/+y1X14gmHNTZJNm8TYmld4QcAvbhKqKp+DKxMslcr2h+4V08IXpB3DFwI+n574yT/CDwV2DbJKuDoqjp+slGNzb7AHwDfb+PiAG9od7rsgx2AZe0KmQ2AU6qqd5fJ9dj2wGe6XJiNgE9U1RcmG9JYvRz4ePvxdzlwxITjmZOXCEqS1FMOB0iS1FMmAZIk9ZRJgCRJPWUSIElST5kESJLUUyYBUk8l2T7J15PcnORvJh3PfEnyd0nePOk4pIXA+wRIC0ySc4EXAXcBp7bbs94TRwE30D3lbt6uFU5yIt1d0940X8dcH1X1p5NoV1qI7AmQFpB2O+LdgBXA44ALfo3D7QZcPJ8JwKS1GxRJGpJJgLSwPIJffnEvZR1JQJLfTnJekpva+2+38hOBw4HXJPlZkqfPsO+mSf4myVVt/2+22wCT5FNJftzKv57k4a38KLpeiqnjfq6V75jk00lWJ7kiySumtbMsydoklyR5TbvL5NT2hyb5apIbk1yU5DkD205M8uEkZyS5BXhaK3vHQJ1nJ7mw7f/tJL81sO21Sa5uQyI/SLL/evwtpIWvqnz58nUvf9HdevRG4FbgtrZ8J3BzW37QDPtsA6ylu4XxRsAL2/oD2vYTgXfM0eYH6R7+sxPdra9/G9ikbfsfwP2ATegem3vhwH53Oy7dj43zgbcA96F73OrlwIFt+7uArwFb0z1o63t0wwkAG9P1eryh7btfO+e9Btq6ie5WzRsA9x1sn+7hLdcDT2jncDhwZYt7L7rHfe/Y6u4OPGTSf2tfvsb5sidAWgCq6iNVtRXdl+k+wG/RPZRly6raqqqumGG3ZwGXVdVHq+rOqvpHugf5HLyu9pJsQPdF/8qqurq6RwN/u6pub/GcUFU3t/W3Ao9Kcv9ZDvd4YElVHVNVd1TV5cA/0D1cB+D3gL+sqrVVtQp4/8C++wBbAO9q+34Z+DxdQjPltKr6VlX9oqpum9b2HwN/X1XntHNYBtzejnsXXTLwsCQbV9WVVfXDdX020mJiEiDdyyXZpnVl30T3a/yrwA/ofsmuTfKqWXbdEbhqWtlVdL/s12Vbul/Vv/KlmGTDJO9K8sMkP6X7ZT21z0x2A3Zs53BjkhvpftlvPxDnyoH6g8s7Aiur6hdznMNg/ZnafvW0tneh+/W/AngVXRJzfZKTk+w4x7GkRcckQLqXq6o1rRfgT4Dj2vIXgINbL8B7Z9n1GrovwUG7AlcP0ewNdMMOD5lh2+8Dh9A9Ivj+dN3oAJkKeVr9lcAVLdap1/2q6plt+7V0wwBTdpl2Dru0nonZzmGuiY0rgXdOa3uz1itCVX2iqn6H7nMq4N1zHEtadEwCpIVj8GqAx9ANDczlDOA3kvx+ko2SvAB4GF13+pzaL+8TgL9tk/o2TPLEJJvQzQW4HfgJsBnwl9N2v45u3H/KucBP2yS8TduxHpHk8W37KcDrk2ydZCfgZQP7ngPcQjfRcOMkT6Ubzjh5XefQ/APwp0mekM7mSZ6V5H5J9kqyXzun24D/pBsikHrDJEBaOB4HXJDkAcBdVbV2rspV9RPg2cCr6b6wXwM8u6puGLK9Pwe+D5wHrKH7lbwBcBJdl/zVwMXA2dP2O55unP3GJJ+tqrvovrgfDVxB18twHF0vAsAxwKq27V+BU+mSDKrqDuA5wDPafh8CXlJVlw5zAlW1nG5ewAfoJkWuAP6wbd6EblLiDcCPge3ohimk3kjVorlEWNIikOR/AodV1VMmHYu02NkTIGmikuyQZN8kGyTZi67n4jOTjkvqA28bLGnS7gP8PfAgunsenEzX7S9pxBwOkCSppxwOkCSpp0wCJEnqKZMASZJ6yiRAkqSeMgmQJKmnTAIkSeqp/w8fIpK/QvcDXwAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 576x360 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "rowsums = dataset.iloc[:,2:].sum(axis=1)\n",
    "x=rowsums.value_counts()\n",
    "#plot\n",
    "plt.figure(figsize=(8,5))\n",
    "ax = sns.barplot(x.index, x.values)\n",
    "plt.title(\"Multiple categories per comment\")\n",
    "plt.ylabel('# of Occurrences', fontsize=12)\n",
    "plt.xlabel('# of categories', fontsize=12)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "C:\\Users\\srisa_000\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation=\"relu\", input_dim=1500, units=6, kernel_initializer=\"uniform\")`\n",
      "  # Remove the CWD from sys.path while we load stuff.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From C:\\Users\\srisa_000\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Colocations handled automatically by placer.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\srisa_000\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation=\"relu\", units=6, kernel_initializer=\"uniform\")`\n",
      "  if sys.path[0] == '':\n",
      "C:\\Users\\srisa_000\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:14: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation=\"sigmoid\", units=6, kernel_initializer=\"uniform\")`\n",
      "  \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From C:\\Users\\srisa_000\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.cast instead.\n",
      "Epoch 1/5\n",
      "4941/4941 [==============================] - 9s 2ms/step - loss: 0.3934 - acc: 0.9753\n",
      "Epoch 2/5\n",
      "4941/4941 [==============================] - 1s 236us/step - loss: 0.3423 - acc: 0.9935ETA: 1s - loss: \n",
      "Epoch 3/5\n",
      "4941/4941 [==============================] - 1s 205us/step - loss: 0.3194 - acc: 0.9935\n",
      "Epoch 4/5\n",
      "4941/4941 [==============================] - 1s 162us/step - loss: 0.3099 - acc: 0.9935\n",
      "Epoch 5/5\n",
      "4941/4941 [==============================] - 1s 155us/step - loss: 0.3049 - acc: 0.9935\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)\n",
    "\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "model = Sequential()\n",
    "\n",
    "\n",
    "\n",
    "model.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 1500))\n",
    "\n",
    "model.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))\n",
    "\n",
    "model.add(Dense(output_dim = 6, init = 'uniform', activation = 'sigmoid'))\n",
    "\n",
    "model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])\n",
    "\n",
    "model.fit(X_train,y_train,batch_size=32,epochs=5)\n",
    "\n",
    "\n",
    "\n",
    "y_pred=model.predict(X_test)\n",
    "\n",
    "y_pred=y_pred>0.5\n",
    "r=model.predict(cv.transform([\"\"]))\n",
    "r=r>0.5\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "model.save(\"project.h5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
